### ISSUE TITLE
SQLCMD should exit on certain errors

### ISSUE THREAD

**Issue by sommarskog** [microsoft/go-sqlcmd#76]
Consider:

RAISERROR('This is the end', 1, 127)

When you run this in the old SQLCMD, the scripts exits, because state is 127. go-sqlcmd does not. (This an old holdover from ISQL, and should still work I think. No, this does not work in SSMS.)

On a similar note:

RAISERROR('Get me out of here!', 20, 1) WITH LOG

This closes the connection to SQL Server, and old SQLCMD exits at this point. go-sqlcmd does not, but nor does it reconnect, so you only get more error messages.

**Comment by shueybubbles** [comment]
This is gonna be a bit tricky.  
Because the severity of this message is <= 10 it is treated as a message instead of an error. 
The `sqlexp.MsgNotice` type only captures the string part of the message, see https://github.com/microsoft/go-mssqldb/blob/39b1cff22838c5a0c85a5e8a196f05e2c462217d/token.go#L815

The `go-mssqldb` driver would need to extend the `sqlexp.MsgNotice` type to provide the missing fields.
